name: Build Devsit
on:
  workflow_dispatch:

jobs:
  build_app:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - appname: dev1
            env: dev1_env
            db_connection: dev1_db
          - appname: dev2
            env: dev2_env
            db_connection: dev2_db
          # - appname: sit1
          #   env: sit1_env
          #   db_connection: sit1_db
          # - appname: sit2
          #   env: sit2_env
          #   db_connection: sit2_db

    outputs:
      artifact_name: ${{ steps.define_artifact.outputs.artifact_name }}

    steps:  
      - name: Checkout Code 
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Build Dotnet
        run: dotnet build -c Release
    
      - name: Publish Dotnet
        run: dotnet publish -c Release -o ./publish_output

      - name: Test command
        run: |
          pwd
          ls ./.github/workflows

      - name: Define artifact
        id: define_artifact
        run: |
          ATF_NAME="Dotnet artifact"
          echo "artifact_name=$ATF_NAME" >> $GITHUB_OUTPUT # Pass value to $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.define_artifact.outputs.artifact_name }}
          path: ./publish_output

  pass_inputs:
    needs: build_app
    uses: ./.github/workflows/deploy.yml
    with:
      appname: ${{ inputs.appname }}
      env: ${{ inputs.env }}
      db_connection: ${{ inputs.db_connection }}
      artifact_name: ${{ needs.build_app.outputs.artifact_name }}