name: Build Dotnet
on:
  workflow_dispatch:
    inputs:
      appname:
        description: 'Enter the appname'
        required: True
        type: string
      env:
        description: 'Enter the environment'
        required: True
        type: string
      db_connection:
        description: 'Enter the database connection'
        required: True
        type: string

jobs:
  build_app:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout Code 
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Build Dotnet
        run: dotnet build -c Release
    
      - name: Publish Dotnet
        run: dotnet publish -c Release -o ./publish_output

      - name: Test command
        run: |
          pwd
          ls ./.github/workflow

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dotnet artifact
          path: ./publish_output

      - name: Pass inputs
        uses: ./.github/workflows/deploy.yml
        with:
          appname: ${{ inputs.appname }}
          env: ${{ inputs.env }}
          db_connection: ${{ inputs.db_connection }}
