name: Build Dotnet
on:
  workflow_dispatch:
    inputs:
      appname:
        description: 'Enter the appname'
        required: True
        type: string
      env:
        description: 'Enter the environment'
        required: True
        type: string
      db_connection:
        description: 'Enter the database connection'
        required: True
        type: string

jobs:
  build-app:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.define_artifact.outputs.artifact_name }}

    steps:  
      - name: Checkout Code 
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Build Dotnet
        run: dotnet build -c Release
    
      - name: Publish Dotnet
        run: dotnet publish -c Release -o ./publish_output

      - name: Test command
        run: |
          pwd
          ls ./.github/workflows

      - name: Define artifact
        id: define_artifact
        run: |
          ATF_NAME="Dotnet artifact"
          echo "artifact_name=$ATF_NAME" >> $GITHUB_OUTPUT # Pass value to $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.define_artifact.outputs.artifact_name }}
          path: ./publish_output

  pass-inputs:
    needs: build-app
    uses: ./.github/workflows/deploy.yml
    with:
      appname: ${{ inputs.appname }}
      env: ${{ inputs.env }}
      db_connection: ${{ inputs.db_connection }}
      artifact_name: ${{ needs.build-app.outputs.artifact_name }}

  test-env:
    runs-on: ubuntu-latest
    environment: ENV_A
    steps:
      run: echo "${{ vars.VAR1 }}"
