name: Call environment

on:
  workflow_call:
    inputs:
      appname:
        type: string
        required: true
    secrets:
      env_vars:
        required: true

jobs:
  show_env:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "appname = ${{inputs.appname}}"
          echo "env_vars = ${{secrets.env_vars}}""