name: Call environment

on:
  workflow_call:
    inputs:
      workspace:
        type: string
        required: true
    secrets:
      env_vars:
        required: true

jobs:
  show_env:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{inputs.workspace}} : ${{secrets.env_vars}}"