name: Call environment

on:
  workflow_call:
    inputs:
      workspace:
        type: string
        required: true
      tf_var:
        type: string
        required: true

jobs:
  show_env:
    runs-on: ubuntu-latest
    environment: ${{ inputs.workspace }}
    steps:
      - run: |
          echo ${{ vars[inputs.tf_var] }}
          echo ${{ inputs.workspace == 'dev' && 'This is true' || 'This is false' }}