name: Deploy Server
on:
  workflow_call:
    inputs:
      appname:
        description: 'Enter the appname'
        required: True
        type: string
      env:
        description: 'Enter the environment'
        required: True
        type: string
      db_connection:
        description: 'Enter the database connection'
        required: True
        type: string

jobs:
  deploy_server:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Dotnet artifact
          path: ./output

      - name: Show output
        run: ls ./output

      - name: Replace fields
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["./output/appsettings.json"]'
        env:
          APP_NAME: This is the APP_NAME
          ENV: This is the ENV!
          DB_CONNECTION: This is the DB_CONNECTION
      - name: Show file
        run: cat ./output/appsettings.json