name: Deploy Devsit
on:
  workflow_call:
    inputs:
      appname:
        description: 'Enter the appname'
        required: True
        type: string
      env:
        description: 'Enter the environment'
        required: True
        type: string
      db_connection:
        description: 'Enter the database connection'
        required: True
        type: string
      artifact_name:
        description: 'Enter the artifact name'
        required: True
        type: string
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact from another workflow
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          name: ${{ inputs.artifact_name }}
          path: ./output

      - name: Show output
        run: |
          ls ./output/dotnet-artifact

      - name: Replace fields
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["./output/appsettings.json"]'
        env:
          APP_NAME: ${{ inputs.appname }}
          ENV: ${{ inputs.env }}
          DB_CONNECTION: ${{ inputs.db_connection }}

      - name: Show file
        run: cat ./output/appsettings.json
