name: Dotnet Pipeline
on:
  workflow_dispatch: # Manually run workflow
  # workflow_call:
  #   inputs:
  #     username:
  #       description: 'A username passed from the caller workflow'
  #       default: 'john-doe'
  #       required: false
  #       type: string

jobs:
  build_app:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout Code 
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Build Dotnet
        run: dotnet build -c Release
    
      - name: Publish Dotnet
        run: dotnet publish -c Release -o ./publish_output

      - name: Test command
        run: echo $GITHUB_WORKSPACE

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dotnet artifact
          path: ./publish_output

  deploy_app:
    needs: build_app
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Dotnet artifact
          path: ./output

      - name: Show output
        run: ls ./output

      - name: Replace fields
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["./output/appsettings.json"]'
        env:
          APP_NAME: This is the APP_NAME
          ENV: This is the ENV!
          DB_CONNECTION: This is the DB_CONNECTION
      - name: Show file
        run: cat ./output/appsettings.json
            