name: Dotnet Pipeline
on:
  workflow_dispatch: # Manually run workflow

jobs:
  build_app:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Code 
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Build Dotnet
        run: dotnet build -c Release
    
      - name: Publish Dotnet
        run: dotnet publish -c Release -o ./publish_output

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dotnet artifact
          path: ./publish_output

  deploy_app:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Dotnet artifact

