name: Dotnet Pipeline
on:
  workflow_dispatch:
    inputs:
      appname:
        description: 'Appname'
        required: true
        type: string
      db_connection:
        description: 'DB_connection'
        required: true
        type: string
      environment:
        description: 'Environment'
        type: environment
        required: true

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if: ${{ inputs.print_tags }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.tags }} 