name: Test environment

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        envs: [E1, E2, E3]

    concurrency:
      group: deploy-envs
      cancel-in-progress: true

    environment: ${{ matrix.envs }}
    
    steps:
      - run: echo "This is the environment ${{ matrix.envs }}"